language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda env create -f slamdunk/environment.yaml
  - source activate slamdunk
  - pip install pytest
  - pip install .

# command to run tests
script:
 - slamdunk -h
 - alleyoop -h
 - splash -h
 - slamdunk/test/test_sample.sh
 - pytest
